version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./furnitureAPI
      dockerfile: Dockerfile
    container_name: furnitureAPI_backend
    restart: always
    env_file:
      - ./furnitureAPI/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mailhog

  frontend:
    build:
      context: ./furnitureApp
      dockerfile: Dockerfile
    container_name: furnitureApp_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
