export { default as Home } from "./Home/Home";
export { default as Login } from "./Login/Login";
export { default as ProtectedPage } from "./Protected/Protected";
export { default as Register } from "./Register/Register";
export { default as AddProject } from "./Addproject/AddProject";
export { default as MyProjects } from "./MyProjects/MyProjects";
export { default as ManageUsers } from "./Admin/ManageUsers/ManageUsers";
export { default as ManageProjects } from "./Admin/ManageProjects/ManageProjects";
export { default as AddDoneImage } from "./Admin/AddDoneImage/AddDoneImage";